name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git config --global user.email "stanley.shen2003@gmail.com"
          git config --global user.name "stanleyshen2003"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/stanleyshen2003/me.git
          npm run deploy

